const database = require('../data/tz.json');

const tzInts = {
    1: "America/Adak",
    2: "America/Anchorage",
    3: "America/Boise",
    4: "America/Chicago",
    5: "America/Denver",
    6: "America/Detroit",
    7: "America/Indiana/Indianapolis",
    8: "America/Indiana/Knox",
    9: "America/Indiana/Marengo",
    10: "America/Indiana/Petersburg",
    11: "America/Indiana/Tell_City",
    12: "America/Indiana/Vevay",
    13: "America/Indiana/Vincennes",
    14: "America/Indiana/Winamac",
    15: "America/Juneau",
    16: "America/Kentucky/Louisville",
    17: "America/Kentucky/Monticello",
    18: "America/Los_Angeles",
    19: "America/Menominee",
    20: "America/Metlakatla",
    21: "America/New_York",
    22: "America/Nome",
    23: "America/North_Dakota/Beulah",
    24: "America/North_Dakota/Center",
    25: "America/North_Dakota/New_Salem",
    26: "America/Phoenix",
    27: "America/Puerto_Rico",
    28: "America/Sitka",
    29: "America/St_Thomas",
    30: "America/Yakutat",
    31: "Pacific/Chuuk",
    32: "Pacific/Guam",
    33: "Pacific/Honolulu",
    34: "Pacific/Kosrae",
    35: "Pacific/Kwajalein",
    36: "Pacific/Majuro",
    37: "Pacific/Pago_Pago",
    38: "Pacific/Palau",
    39: "Pacific/Pohnpei",
    40: "Pacific/Saipan",
    41: "Pacific/Wake",
}

exports.lookup = (zipcode) => {
    return tzInts[database[zipcode] ?? null] ?? null;
};